controller_list:
  - name: arm_1/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
    constraints:
      goal_time: 5.0                   # Override default
      stopped_velocity_tolerance: 0.0 # Override default
      arm_joint_1: {trajectory: 0.05, goal: 1.0}
      arm_joint_2: {trajectory: 0.05, goal: 1.0}
      arm_joint_3: {trajectory: 0.05, goal: 1.0}
      arm_joint_4: {trajectory: 0.05, goal: 1.0}
      arm_joint_5: {trajectory: 0.05, goal: 1.0}
    gains: # Required because we're controlling an effort interface
      arm_joint_1: {p: 100,  d: 1, i: 1, i_clamp: 1}
      arm_joint_2: {p: 100,  d: 1, i: 1, i_clamp: 1}
      arm_joint_3: {p: 100,  d: 1, i: 1, i_clamp: 1}
      arm_joint_4: {p: 100,  d: 1, i: 1, i_clamp: 1}
      arm_joint_5: {p: 100,  d: 1, i: 1, i_clamp: 1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
  - name: arm_1/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
