controller_list:
  - name: arm_1
    action_ns: arm_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.01 # Override default
    gains: # Required because we're controlling an effort interface
      arm_joint_1: {p: 20,  d: 0, i: 1, i_clamp: 1}
      arm_joint_2: {p: 20,  d: 0, i: 1, i_clamp: 1}
      arm_joint_3: {p: 20,  d: 0, i: 1, i_clamp: 1}
      arm_joint_4: {p: 20,  d: 0, i: 10, i_clamp: 1}
      arm_joint_5: {p: 20,  d: 0, i: 1, i_clamp: 1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  100
    action_monitor_rate: 10
