youbot_arm:
  kinematics_solver: youbot_arm_kinematics_moveit::KinematicsPlugin # Youbot Kinematic Plugin from Sven Schneider
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
