# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - virtual_joint
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
    - gripper_finger_joint_l
    - gripper_finger_joint_r
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
youbot_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_finger_joint_l
    - gripper_finger_joint_r
  gains:
    gripper_finger_joint_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_finger_joint_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
youbot_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1